---
resources:
- name: my_repo
  type: git
  source:
    uri: https://github.com/mhtike/simple-go-web-app.git
    branch: master

- name: pas
  type: cf
  source:
    api: ((cf-api))
    username: ((cf-username))
    password: ((cf-password))
    organization: ((cf-organization))
    space: ((cf-space))
    skip_cert_check: true

jobs:
- name: deploy-app
  serial: true
  plan:
  - get: my_repo
  - put: pas
    params:
      manifest: my_repo/manifest.yml
      path: my_repo


#
#
#
# ---
# resources:
# - name: app
#   type: git
#   source:
#     uri: https://github.com/mhtike/simple-go-web-app.git
#
# - name: deploy-web-app
#   type: cf
#   source:
#     api: ((cf-api))
#     username: ((cf-username))
#     password: ((cf-password))
#     organization: ((cf-organization))
#     space: ((cf-space))
#     skip_cert_check: true
#
# jobs:
# - name: deploy-app
#   public: true
#   serial: true
#   plan:
#   - get: app
#     trigger: true
#   - task: web-app-tests
#     config:
#       platform: linux
#
#       image_resource:
#         type: docker-image
#         source: {repository: golang, tag: 1.9-alpine}
#
#       inputs:
#       - name: app
#         path: gopath/src/github.com/mhtike/simple-go-web-app
#
#   - put: deploy-web-app
#     params:
#       manifest: app/manifest.yml
#       path: app
